on:
    push:
        branches:
            - '*'

jobs:
    test_job:
        runs-on: ubuntu-latest
        environment: dev
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with: 
            cache: 'npm'
        - run: npm i
        - name: Salesforce Login
          uses: ./custom-github-action/salesforce-login
          with: 
            url: ${{secrets.SALESFORCE_URL}}
            username: ${{secrets.SALESFORCE_USERNAME}}
            password: ${{secrets.SALESFORCE_PASSWORD}}
           
