on:
    push:
        branches:
            - '*'

jobs:
    test_job:
        runs-on: ubuntu-latest
        steps:
            - name: Check directory
            run: ls -l
            shell: bash
            - uses: ./custom-github-action/action1/