on:
    push:
        branches:
            - '*'

jobs:
    test_job:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: ./custom-github-action/action1
        - uses: ./custom-github-action/action2
            