on:
    push:
        branches:
            - '*'

jobs:
    test_job:
        runs-on: ubuntu-latest
        environment: dev
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
        - run: npm ci
        - name: Salesforce Login
          uses: ./custom-github-action/salesforce-login
          with: 
            orgType: ${{secrets.SALESFORCE_ORG_TYPE}}
            apiVersion: ${{secrets.SALESFORCE_API_VERSION}}
            username: ${{secrets.SALESFORCE_USERNAME}}
            password: ${{secrets.SALESFORCE_PASSWORD}}
           
